name: Deno Server and Curl Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.18.1'

      - name: Start Deno Server
        run: |
          deno run --allow-net sabatwi.js & echo $! > deno_pid
          sleep 5 # Wait for Deno server to start

      - name: Test Connection with Curl
        run: |
          curl http://localhost:8000 # Replace with your Deno server URL
          curl_exit_code=$?
          if [ $curl_exit_code -ne 0 ]; then
            echo "Curl failed with exit code $curl_exit_code"
            exit 1
          fi

      - name: Stop Deno Server
        run: kill -9 $(cat deno_pid)
